spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql:localhost:3306/datamarketplace
    username: datamarketplace
    password: datamarketplace

liquibase:
  change-log: classpath:db/changelog/liquibase-changelog.xml
